apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  labels:
    app: loki
    argocd.argoproj.io/instance: tools
spec:
  selector:
    matchLabels:
      app: loki
  serviceName: loki
  template:
    metadata:
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
      labels:
        app: loki
        name: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.7.0
          #imagePullPolicy: Always
          args:
            - "-config.file=/etc/loki/loki.yml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki/loki.yml
              subPath: loki.yml
          ports:
            - containerPort: 3100
          resources:
            limits:
              cpu: 100m
              memory: 900Mi
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            name: loki-config
            items:
            - key: loki.yml
              path: loki.yml