apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: limit-range-example
spec:
  containers:
  - image: nginx:1.21
    name: nginx
    resources:
      requests:
        memory: 2Gi
        cpu: 3
      limits:
        memory: 256Mi
        cpu: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
