apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagina-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagina-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: imagina-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagina-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: imagina-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: imagina-scheduler-extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: imagina-scheduler
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imagina-scheduler-config
  namespace: kube-system
data:
  imagina-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: imagina-scheduler
        plugins:
          filter:
            disabled:
            - name: NodeUnschedulable
            - name: TaintToleration
    leaderElection:
      leaderElect: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: imagina-scheduler
  name: imagina-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: imagina-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        component: imagina-scheduler
    spec:
      serviceAccountName: imagina-scheduler
      containers:
      - command:
        - kube-scheduler
        - --config=/etc/kubernetes/imagina-scheduler/imagina-scheduler-config.yaml
        image: registry.k8s.io/kube-scheduler:v1.26.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: imagina-otro-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.5'
        securityContext:
          privileged: false
        volumeMounts:
          - name: config-volume
            mountPath: /etc/kubernetes/imagina-scheduler
      hostNetwork: false
      hostPID: false
      imagePullSecrets:
      - name: disa-reg-cred
      volumes:
        - name: config-volume
          configMap:
            name: imagina-scheduler-config