apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: imagina-world-custom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: imagina-world
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: nginx_ingress_controller_requests_per_second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: imagina-world
      target:
        type: AverageValue
        value: 500m
  - type: Pods
    pods:
      metric:
        name: cpu_system
      target:
        type: AverageValue
        averageValue: 200m
