apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: custom-metrics
  labels:
    app: gitaly
    app.kubernetes.io/managed-by: Helm
    chart: gitaly-6.7.1
    heritage: Helm
    release: gitlab
  name: gitlab-gitaly
  namespace: custom-metrics
spec:
  ports:
  - name: tcp-gitaly
    port: 8075
    protocol: TCP
    targetPort: grpc-gitaly
  - name: http-metrics
    port: 9236
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: gitaly
    release: gitlab
  sessionAffinity: None
  type: NodePort
