apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio
  labels:
    app: minio
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: gitlab-minio
    namespace: custom-metrics
  nfs:
    server: 192.168.1.148
    path: "/home/usuario/gitlab/minio"
