apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-gitlab-postgresql-0
  labels:
    app: postgres
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-gitlab-postgresql-0
    namespace: custom-metrics
  nfs:
    server: 192.168.1.148
    path: "/home/usuario/gitlab/postgres"
