apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-gitlab-redis-master-0
  labels:
    app: redis
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: redis-data-gitlab-redis-master-0
    namespace: custom-metrics
  nfs:
    server: 192.168.1.148
    path: "/home/usuario/gitlab/redis"
