apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-exporter
  name: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - image: percona/mongodb_exporter:0.20
        name: mongodb-exporter
        env:
        - name: MONGODB_URI
          value: "mongodb://imagina:imagina@mongodb-service:27017"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
spec:
  selector:
    app: mongodb-exporter
  ports:
  - protocol: TCP
    port: 9216
    targetPort: 9216

