apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: selector1
  name: nginx
spec:
  containers:
  - image: nginx:1.21
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
