apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-workflowtemplate-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-workflowtemplate-role
subjects:
- kind: ServiceAccount
  name: workflow
  namespace: argo-events
---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-workflowtemplate-role
rules:
- apiGroups:
  - ""
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - workflowtaskresults
  - pods
  verbs:
  - create
  - delete
  - watch
  - get
  - list
  - watch
  - patch