apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "privileged"
      enforce-version: "v1.25"
      audit: "privileged"
      audit-version: "v1.25"
      warn: "privileged"
      warn-version: "v1.25"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: ["tema13"]
