kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagina1
subjects:
- kind: User
  name: imagina1
roleRef:
  kind: ClusterRole
  name: imagina1
  apiGroup: rbac.authorization.k8s.io
