kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagina
  namespace: tema13
subjects:
- kind: User
  name: imagina
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: imagina
  apiGroup: rbac.authorization.k8s.io
