apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imagina-nginx-privilege
  name: imagina-nginx-privilege
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: imagina-nginx-privilege  
  template:
    metadata:
      labels:
        app: imagina-nginx-privilege
    spec:
      containers:
        - name: imagina-nginx-privilege    
          image: nginx:1.21
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: true
