apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: imagina-test
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "clave1"
    operator: "Equal"
    value: "valor1"
    effect: "NoSchedule"
  - key: "clave1"
    operator: "Equal"
    value: "valor1"
    effect: "NoExecute"
  - key: "clave2"
    operator: "Equal"
    value: "valor2"
    effect: "NoExecute"
    tolerationSeconds: 10
