apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-pv
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.144
    path: "/home/usuario/nginx-nfs"
