apiVersion: v1
kind: ReplicationController
metadata:
  name: imagina-nginx
spec:
  replicas: 5
  selector:
    app: imagina-nginx
  template:
    metadata:
      name: imagina-nginx
      labels:
        app: imagina-nginx
    spec:
      containers:
      - name: imagina-nginx
        image: nginx:1.21
        ports:
        - containerPort: 80