apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: wordpress
  template:
    metadata:
      labels:
        tier: frontend
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80

