apiVersion: v1
kind: Pod
metadata:
  name: imagina-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /cache
      name: app-volume
  - name: nginx2
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /tmp
      name: app-volume
    - mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      name: nginx-config
  nodeSelector:
    kubernetes.io/hostname: worker2
  volumes:
  - name: app-volume
    hostPath:
        path: /tmp/
  - name: nginx-config
    configMap:
      name: nginx
      items:
      - key: default.conf
        path: default.conf
