apiVersion: v1
kind: Pod
metadata:
  name: imagina-ssh
spec:
  containers:
  - name: ssh
    image: kroniak/ssh-client
    command: ["/bin/sh","-c"]
    args: ["sleep 1000"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/secret-volume
      readOnly: true
      name: ssh-key
  volumes:
  - name: ssh-key
    secret:
        secretName: ssh-key-secret
