apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-mon
    app.kubernetes.io/component: cephclusters.ceph.rook.io
    app.kubernetes.io/created-by: rook-ceph-operator
    app.kubernetes.io/instance: a
    app.kubernetes.io/managed-by: rook-ceph-operator
    app.kubernetes.io/name: ceph-mon
    app.kubernetes.io/part-of: rook-ceph
    ceph_daemon_id: a
    ceph_daemon_type: mon
    mon: a
    mon_cluster: rook-ceph
    rook.io/operator-namespace: rook-ceph
    rook_cluster: rook-ceph
  name: rook-ceph-mon-a
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    kind: CephCluster
    name: rook-ceph
    uid: 169991cf-ca2a-4834-8a8e-fef6ad9231fe
  resourceVersion: "4726090"
  uid: c20fefff-1307-4be7-a67b-c5f46e534be5
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-msgr1
    port: 6789
    protocol: TCP
    targetPort: 6789
    nodePort: 31789
  - name: tcp-msgr2
    port: 3300
    protocol: TCP
    targetPort: 3300
    nodePort: 31300
  selector:
    app: rook-ceph-mon
    ceph_daemon_id: a
    mon: a
    mon_cluster: rook-ceph
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: NodePort
