kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata: 
  name: imagina-civo-crossplane
spec:
  name: imagina-civo-crossplane
  pools:
    - id: "8382e422-dcdd-461f-afb4-2ab67f171c3e"
      count: 1
      size: g3.k3s.xsmall
  applications: 
    - "argo-cd"
  version: "1.23.6-k3s1"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider
