apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbs.stable.imagina.io
spec:
  group: stable.imagina.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                ip:
                  type: string
                user:
                  type: string
                password:
                  type: string
                table:
                  type: string
                column:
                  type: string
  scope: Namespaced
  names:
    plural: dbs
    singular: database
    kind: Database
    shortNames:
    - db
